---
- include: playbook_simpleshell.yml
- hosts: myhosts
  tasks:
  - name: Run a command
    command: ls -l    
    register: outputVar
  - name: Clear dirs
    file: name=/tmp/{{ item }} state=absent
    with_items:
    - dir1
    - dir2
    - dir3
    - dir4
    - dir5
  - name: Make dirs
    file: name=/tmp/{{ item }} state=directory
    with_items:
    - dir1
    - dir2
    - dir3
    - dir4
    - dir5
 
