# Play book for various package manipulation. 
---
- hosts: localhost
  tasks:
  - name: Install some GEMs - add
    gem: name=vagrant state=present

  - name: Install some GEMs - remove
    gem: name=vagrant state=absent

  - name: Install some GEMs - put back
    gem: name=vagrant state=present

  #- cpanm: name=Dancer