# Play book for users, but will not work on mac as Ansible has issues with lack of useradd
# Also does not work for groups on Mac
---
- hosts: myhosts
  vars:
     passWd: aPassword123

  tasks:
  - name: Add a group
    group: name=lala
  - name: Drop a group
    group: name=lala state=absent
  - name: Create a user
    action: user name=anewuser group=users shell=/bin/bash createhome=no comment="This is a user" password={{passWd}}
  - name: Update a user
    action: user name=anewuser comment="This is an update"
  - name: Delete a user
    action: user name=anewuser state=absent    
  - name: Create a user again
    user: name=fred shell=/bin/bash
  - name: Change shell
    command: /usr/bin/chsh -s /usr/bin/sh fred
  - name: Delete a user again
    user: name=fred state=absent

