---
- hosts: myhosts
  vars:
    hitomi: anime
    silent_mobius: Yuki
  roles:
  - { role: aRole, param1: 1, param2: 2, tags: [ 'a', 'b' ] }
  tasks:
  - name: Exterminate-1
    action: exterminate.py darlek=the-controller exterminate_mode=bychainsaw
    register: exterminatedBy
  - name: Extermined-by
    debug: msg="{{exterminatedBy}}"
  - name: Exterminate-2
    action: exterminate.py darlek=the-controller exterminate_mode=bydarlek
    register: exterminatedBy
  - name: Extermined-by
    debug: msg="{{exterminatedBy}}"
