---
- hosts: myhosts
  vars:
    env:
      ORACLE_HOME: /Volumes/Hitomi/tpayne/work/Oracle/instantclient_11_2
      DYLD_LIBRARY_PATH: /Volumes/Hitomi/tpayne/work/Oracle/instantclient_11_2
      LD_LIBRARY_PATH: /Volumes/Hitomi/tpayne/work/Oracle/instantclient_11_2
  tasks:
  - name: SQLFile-1
    environment: env
    action: oracle.py hostName=192.168.0.17 sqlUser=pcms_sys sqlPwd=pcms_sys port=1521 tns=dim12 sqlFile=/tmp/i.sql logFile=STDOUT
    register: sqlOut
  - name: Output
    debug: msg="{{sqlOut}}"
