---
- include: playbook_simpleshell.yml
  when: '"ansible_os_family" == "Darwin"'
- hosts: myhosts
  handlers:
  - name: debug-something
    debug: msg='All is debug...'
  - name: Start-service
    service: state=started name=nginx
  - name: opps-worked
    debug: msg='All is not well'
  tasks:
  - name: Run a command
    command: ls -l    
    register: outputVar
  - name: Show something special
    shell: echo "This is a debugging task. What happens when it ends?"
    notify:
    - debug-something
  # Option to force the handlers to be flushed if wanted
  - meta: flush_handlers
  - name: Clear dirs
    file: name=/tmp/{{ item }} state=absent
    with_items:
    - dir1
    - dir2
    - dir3
    - dir4
    - dir5
  - name: Make dirs
    file: name=/tmp/{{ item }} state=directory
    with_items:
    - dir1
    - dir2
    - dir3
    - dir4
    - dir5
  - name: Start-service
    service: state=started name=nginx
    register: outputTxt
    ignore_errors: yes
  - name: Print-task
    debug: msg="{{ outputTxt }}"
  - name: It-failed
    debug: msg="It failed"
    when: outputTxt|failed





