---
- hosts: myhosts
  vars_prompt:
    - name: PostgresqlPwd
      prompt: "Postgres Password"
      default: "postgres"  
  vars:
    postgres_host: localhost
  tasks:
  - name: Print out Postgres facts
    action: postgresql_facts.py pgserver={{postgres_host}} pgport=5432 pguser=postgres pguserpwd={{PostgresqlPwd}} pgdb=test 
    register: sqlOut
  - name: Output the results
    debug: msg="{{sqlOut}}"