---
- name: Hello-Goodbye
  debug: msg="Hello and goodbye"
- name: Install GEM
  gem: name=rake state=latest
- name: Install template
  template: src=conf.j2 dest=/tmp/config.deployed
- shell: echo param1={{ param1 }}, param2 ={{ param2 }}
